### PR TITLE
Same correction as previous pull from "brematurata" to "prematurata" for all other examples

### PR DESCRIPTION
**Pull request by calamarim**
This to have an homogeneous feature in example with the new "supercazzola" instad of old "supercazzora"

### CODE REVIEW

**Comment by esseks** [comment]
Would you mind squashing all commits in one?

**Comment by shineangelic** [comment]
I believe brematurata is correct, as well as supercazzora

**Comment by shineangelic** [comment]
It's a miss-spelling born from the movie, but on the book it's definitely supercazzora Brematurata
https://it.wikipedia.org/wiki/Supercazzola

**Comment by tonjo** [comment]
I see, but the language is called Monicelli, the movie author, not the book writer :P

**Comment by tonjo** [comment]
Moreover, the book came AFTER the movie.

**Comment by mferretti** [comment]
The word is "supercazzora" it's just the the actor is too quick. Please have a look at the only time it is written (in the movie)  https://www.youtube.com/watch?v=Bc8WS2LjR3g ; ~45 seconds

**Comment by shineangelic** [comment]
> Moreover, the book came AFTER the movie.

yes, correct, but the book comes from the same authors, one year after the first movie (1976) so that's a good source for 'official' spelling of the term. Also note @mferretti comment, it's definitely supercazzoRa

**Comment by tonjo** [comment]
The best thing is: we keep posting in English about something that makes
sense only in Italian.
I love you guys, I love you immortal genius MM.


Il giorno ven 14 dic 2018 alle ore 14:48 Alessandro Del Pex <
notifications@github.com> ha scritto:

**Comment by esseks** [comment]
Closing as stale.

**Pull request closed without merging**
